apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::889719319920:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-WNFAG27VHNIO
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::889719319920:role/UdacityFlaskDeployCBKubectlRole
      username: build      

kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-25T02:16:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1625"
  uid: 0ecdbac6-141b-43ef-af9b-c7ffbd5d07b7
